name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - release
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 17
          distribution: temurin

      # AM (SYNC_DRIVE) -->
      - name: Write client_secrets.json
        uses: DamianReeves/write-file-action@v1.2
        with:
            path: app/src/main/assets/client_secrets.json
            contents: ${{ secrets.CLIENT_SECRETS_TEXT }}
            write-mode: overwrite
      # <-- AM (SYNC_DRIVE)

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Build app
        run: ./gradlew assembleRelease -Penable-updater

      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest

      - name: Upload APK
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: arm64-v8a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk

      - name: Upload mapping
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/release

      # Sign APK and create release for tags

      - name: Get tag name

        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Quickdesh/Animiru'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Quickdesh/Animiru'
        uses: r0adkll/sign-android-release@f30bdd30588842ac76044ecdbd4b6d0e3e813478
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '35.0.1'

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Quickdesh/Animiru'
        run: |
          set -e

          mv app/build/outputs/apk/release/app-universal-release-unsigned-signed.apk Animiru-${{ env.VERSION_TAG }}.apk
          mv app/build/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk Animiru-arm64-v8a-${{ env.VERSION_TAG }}.apk
          mv app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned-signed.apk Animiru-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          mv app/build/outputs/apk/release/app-x86-release-unsigned-signed.apk Animiru-x86-${{ env.VERSION_TAG }}.apk
          mv app/build/outputs/apk/release/app-x86_64-release-unsigned-signed.apk Animiru-x86_64-${{ env.VERSION_TAG }}.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Quickdesh/Animiru'
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Animiru ${{ env.VERSION_TAG }}
          body: |
            Check out the [past release notes](https://github.com/quickdesh/Animiru/releases) if you’re upgrading from an earlier version.

            <!-->



            <!-->

            > [!TIP]
            >
            > ### If you are unsure which version to download then go with `Animiru-${{ env.VERSION_TAG }}.apk`

          files: |
            Animiru-${{ env.VERSION_TAG }}.apk
            Animiru-arm64-v8a-${{ env.VERSION_TAG }}.apk
            Animiru-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            Animiru-x86-${{ env.VERSION_TAG }}.apk
            Animiru-x86_64-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
